In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df = pd.read_csv('telecom_churn.csv')

In [19]:
df.head()

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,0,128,1,1,2.7,1,265.1,110,89.0,9.87,10.0
1,0,107,1,1,3.7,1,161.6,123,82.0,9.78,13.7
2,0,137,1,0,0.0,0,243.4,114,52.0,6.06,12.2
3,0,84,0,0,0.0,2,299.4,71,57.0,3.10,6.6
4,0,75,0,0,0.0,3,166.7,113,41.0,7.42,10.1

In [20]:
df.columns = df.columns.str.strip()

In [21]:
df.shape

(3333, 11)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Churn            3333 non-null   int64
 1   AccountWeeks     3333 non-null   int64
 2   ContractRenewal  3333 non-null   int64
 3   DataPlan         3333 non-null   int64
 4   DataUsage        3333 non-null   float64
 5   CustServCalls    3333 non-null   int64
 6   DayMins          3333 non-null   float64
 7   DayCalls         3333 non-null   int64
 8   MonthlyCharge    3333 non-null   float64
 9   OverageFee       3333 non-null   float64
 10  RoamMins         3333 non-null   float64
dtypes: float64(5), int64(6)
memory usage: 286.6 KB

In [23]:
df.isnull().sum()

Churn              0
AccountWeeks       0
ContractRenewal    0
DataPlan           0
DataUsage          0
CustServCalls      0
DayMins            0
DayCalls           0
MonthlyCharge      0
OverageFee         0
RoamMins           0
dtype: int64

In [24]:
df['Churn'].isnull().sum()

np.int64(0)

In [25]:
df.duplicated().sum()

np.int64(0)

In [28]:
df['Churn'] = df['Churn'].map({0: "Service in Use", 1:"Service not in use"})

In [29]:
df.head(3)

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,Service in Use,128,1,1,2.7,1,265.1,110,89.0,9.87,10.0
1,Service in Use,107,1,1,3.7,1,161.6,123,82.0,9.78,13.7
2,Service in Use,137,1,0,0.0,0,243.4,114,52.0,6.06,12.2

In [30]:
df['Churn'].value_counts()

Churn
Service in Use        2850
Service not in use     483
Name: count, dtype: int64

In [31]:
X = df.drop('Churn', axis = 1)

In [32]:
y = df['Churn']

In [33]:
X

,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
0,128,1,1,2.70,1,265.1,110,89.0,9.87,10.0
1,107,1,1,3.70,1,161.6,123,82.0,9.78,13.7
2,137,1,0,0.00,0,243.4,114,52.0,6.06,12.2
3,84,0,0,0.00,2,299.4,71,57.0,3.10,6.6
4,75,0,0,0.00,3,166.7,113,41.0,7.42,10.1
...,...,...,...,...,...,...,...,...,...,...
3328,192,1,1,2.67,2,156.2,77,71.7,10.78,9.9
3329,68,1,0,0.34,3,231.1,57,56.4,7.67,9.6
3330,28,1,0,0.00,2,180.8,109,56.0,14.44,14.1
3331,184,0,0,0.00,2,213.8,105,50.0,7.98,5.0
3332,74,1,1,3.70,0,234.4,113,100.0,13.30,13.7

In [34]:
y

0       Service in Use
1       Service in Use
2       Service in Use
3       Service in Use
4       Service in Use
             ...
3328    Service in Use
3329    Service in Use
3330    Service in Use
3331    Service in Use
3332    Service in Use
Name: Churn, Length: 3333, dtype: object

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [37]:
X_train.shape

(2333, 10)

In [38]:
X_test.shape

(1000, 10)

In [43]:
X.describe()

,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
count,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000,3333.000000
mean,101.064806,0.903090,0.276628,0.816475,1.562856,179.775098,100.435644,56.305161,10.051488,10.237294
std,39.822106,0.295879,0.447398,1.272668,1.315491,54.467389,20.069084,16.426032,2.535712,2.791840
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,0.000000,0.000000
25%,74.000000,1.000000,0.000000,0.000000,1.000000,143.700000,87.000000,45.000000,8.330000,8.500000
50%,101.000000,1.000000,0.000000,0.000000,1.000000,179.400000,101.000000,53.500000,10.070000,10.300000
75%,127.000000,1.000000,1.000000,1.780000,2.000000,216.400000,114.000000,66.200000,11.770000,12.100000
max,243.000000,1.000000,1.000000,5.400000,9.000000,350.800000,165.000000,111.300000,18.190000,20.000000

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier
)
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

models = {
    "Logistic Regression": LogisticRegression(
        max_iter=2000,
        random_state=42
    ),
    "Random Forest": RandomForestClassifier(
        n_estimators=200,
        random_state=42,
    ),
    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    ),
    "Gradient Boosting": GradientBoostingClassifier(
        random_state=42
    )
}


trained_models = []

for name, model in models.items():
    model.fit(X_train_scaled, y_train)
    y_pred = model.predict(X_test_scaled)
    accuracy = accuracy_score(y_test, y_pred)
    trained_models.append((name, accuracy))
    print(f"\n {name}: {accuracy:.4f}")
print(classification_report(y_test, y_pred))

trained_models.sort(key = lambda x: x[1], reverse=True)
print("\n Ranking:")
for i, (name, accuracy) in enumerate (trained_models, 1):
    print(f"{i}. {name} - {accuracy:.4f}")

 Logistic Regression: 0.8670

 Random Forest: 0.9390

 Decision Tree: 0.8820

 Gradient Boosting: 0.9430
                    precision    recall  f1-score   support

    Service in Use       0.95      0.99      0.97       857
Service not in use       0.89      0.69      0.77       143

          accuracy                           0.94      1000
         macro avg       0.92      0.84      0.87      1000
      weighted avg       0.94      0.94      0.94      1000


 Ranking:
1. Gradient Boosting - 0.9430
2. Random Forest - 0.9390
3. Decision Tree - 0.8820
4. Logistic Regression - 0.8670

In [62]:
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler

In [66]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [67]:
model = GradientBoostingClassifier(random_state = 42)

In [68]:
train_scores = cross_val_score(model, X_train_scaled, y_train, cv= 5, scoring = 'f1_weighted')
test_score = model.fit(X_train_scaled, y_train).score(X_test_scaled, y_test)

In [73]:
print(f"CV Train F1: {train_scores.mean():.4f} +/- {train_scores.std():.4f}")
print(f"Test F1:{test_score:.4f}")

CV Train F1: 0.9262 +/- 0.0066
Test F1:0.9430

In [74]:
import joblib

In [78]:
joblib.dump(model,'gradient_boosting_final.pkl')
joblib.dump(scaler, 'scaler_final.pkl')

['scaler_final.pkl']

In [79]:
print(" Saved - ready for deployment")

 Saved - ready for deployment

In [80]:
import joblib

In [81]:
import sklearn

In [83]:
print(sklearn.__version__)

1.7.2

In [84]:
import joblib

In [85]:
joblib.dump(model, 'gradient_boosting_final.pkl')
joblib.dump(scaler,'scaler_final.pkl')

['scaler_final.pkl']

In [88]:
print("Resaved with",__import__('sklearn').__version__)

Resaved with 1.7.2

In [89]:
import os

In [90]:
print(os.getcwd())

C:\Users\PC\OneDrive\Desktop

In [91]:
import joblib
import sklearn

In [92]:
print(sklearn.__version__)

1.7.2

In [93]:
joblib.dump(model, 'gradient_boosting_final.pkl')
joblib.dump(scaler, 'scaler_final.pkl')

['scaler_final.pkl']